intents = {
    "intents": [
        {
            "tag": "greeting",
            "patterns": [
                "Hi",
                "Hey",
                "Hello",
                "How are you",
                "Is anyone there?",
                "Good day",
            ],
            "responses": [
                "Hey, user",
                "Hello user, thanks for visiting",
                "Hi there, user, what can I do for you?",
                "Hi there, user, how can I help?",
                "Hello user, welcome to infinite possibilities. How can I help you today?",
            ],
        },
        {
            "tag": "goodbye",
            "patterns": ["Bye", "See you later", "Goodbye"],
            "responses": [
                "See you later, thanks for visiting",
                "Have a nice day",
                "Bye! Come back again soon",
            ],
        },
        {
            "tag": "thanks",
            "patterns": ["Thanks", "Thank you", "That's helpful", "Thanks a lot!"],
            "responses": ["Happy to help!", "Anytime!", "My pleasure"],
        },
        {
            "tag": "booking",
            "patterns": [
                "I would like to make a reservation",
                "Can I book a flight?",
                "Book me a flight",
                "I want to make a booking",
                "I want to purchase airline tickets",
                "Book me plane tickets",
            ],
            "responses": [
                "Sure, I only need to know a few details. Where are you headed?",
                "Lovely. Let's begin with the reservation. Where would you want to go?",
                "Lovely. Let's begin with the reservation. Can you speak your current location?",
                "Lovely. Let's begin with the reservation. What is your origin of the flight?",
                "Lovley, should I book from your current location?",
                "And where would you want to fly from ?",
            ],
        },
        {
            "tag": "booking_info_origin",
            "patterns": [
                "I want to book from my current location",
                "I am going from Karachi",
                "I am going from New York",
                "I am based in Delhi , so i would be flying from there",
                "Yes please use my current location",
            ],
            "responses": ["Almost getting there. And where are you headed?"],
        },
        {
            "tag": "booking_info_desination",
            "patterns": [
                "Book me a flight to New York",
                "Can you please book me a plane ticket to Vermont",
                "I want to travel to Bangkok",
                "I want to go to Vermont",
                "I am flying to Chicago",
                "Brooklyn is where I would want to go " "Karachi",
                "New York",
            ],
            "responses": [
                "Amazing. When are you planning to leave?",
            ],
        },
        {
            "tag": "booking_dates_leave",
            "patterns": [
                "I am leaving on 17th Januray",
                "I would be needng tickets for 21st February",
                "I want booking for 25th March",
                "I am leaving on 21th April",
                "I am leaving on 22th May",
                "I am leaving on 6th June",
                "I am leaving on 17th July",
                "I am leaving on 1st August",
                "I am leaving on 2nd September",
                "I am leaving on 17th October",
                "I am leaving on 12th November",
                "I am leaving on 31st Decemeber",
            ],
            "responses": [
                "Lovley time to travel, And return when",
                "Is it a return ticket?",
            ],
        },
        {
            "tag": "booking_dates_return_yes",
            "patterns": [
                "Yes, I will be coming back on April the 14th",
                "Yes, I will be needing round way tickets for October 12th",
                "I am coming back on 17th Januray",
                "I would be needng tickets for 21st February",
                "I want booking for 25th March",
                "I am returning on 21th April",
                "I am coming back on 22th May",
                "I am returning 6th June",
                "I am returning on 17th July",
                "I am heading back on 1st August",
                "I am coming back 2nd September",
                "I am retunring 17th October",
                "I am returning on 12th November",
                "I am returning on 31st Decemeber",
            ],
            "responses": [
                "Perfect, hold on. I'll be back in a few seconds. So you would want to go from origin to destination on traveldate and return on backdate. Should I proceed? "
            ],
        },
        {
            "tag": "booking_confirmation",
            "patterns": [
                "Yes , the details are correct",
                "Yes, please proceed with the booking",
            ],
            "responses": ["Alright, please wait. How many passengers are there?"],
        },
        {
            "tag": "booking_number_of_passengers_alone",
            "patterns": ["I am travelling alone", "It would only be me."],
            "responses": ["Perfect.Should I use to current credit card for booking?"],
        },
        {
            "tag": "booking_number_of_passengers_more",
            "patterns": [
                "I have two kids and two adults",
                "Yes there are more people with me, three kids and three adults",
            ],
            "responses": [
                "Please state the ages of the childrens if any and Should I use to current credit card for booking?"
            ],
        },
        {
            "tag": "booking_bank_details_yes",
            "patterns": [
                "Yes use my current card",
                "Yes you can use my current details",
                "Ye charge my current card",
            ],
            "responses": ["Perfect. Fetching flights"],
        },
        {
            "tag": "booking_confirmation_final",
            "patterns": [
                "Yes you got my preference right",
                "Yes, I liked the flight option",
                "Yes please proceed with the booking",
            ],
            "responses": ["Sure, can you please speak the phrase?"],
        },
        {
            "tag": "unknown",
            "patterns": ["The sky is painted blue", "Earth is moon"],
            "responses": ["I am not sure If i understand you, can you speak again?"],
        },
        {
            "tag": "identification",
            "patterns": [
                "Who are you?",
                "Why are you?",
                "What can you do?",
                "Are you real?",
            ],
            "responses": [
                "I am here to help you book tickets",
                "I am at your service, you can call me Sara.",
            ],
        },
        {
            "tag": "cancellation",
            "patterns": [
                "I would like to cancel my flight",
                "I would like to cancel my booking",
                "I need to cancel my flight",
                "I need to cancel my booking",
                "I would need you to cancel my booking",
            ],
            "responses": ["Sure, can you please say your reference number for me?"],
        },
    ]
}
tags = [
    "booking",
    "booking_bank_details_yes",
    "booking_confirmation",
    "booking_confirmation_final",
    "booking_dates_leave",
    "booking_dates_return_yes",
    "booking_info_desination",
    "booking_info_origin",
    "booking_number_of_passengers_alone",
    "booking_number_of_passengers_more",
    "cancellation",
    "goodbye",
    "greeting",
    "identification",
    "thanks",
    "unknown",
]


all_words = [
    "'s",
    "12th",
    "14th",
    "17th",
    "1st",
    "21st",
    "21th",
    "22th",
    "25th",
    "2nd",
    "31st",
    "6th",
    "a",
    "adult",
    "airlin",
    "alon",
    "am",
    "and",
    "anyon",
    "april",
    "are",
    "august",
    "back",
    "bangkok",
    "base",
    "be",
    "blue",
    "book",
    "brooklyn",
    "bye",
    "can",
    "cancel",
    "card",
    "charg",
    "chicago",
    "come",
    "correct",
    "current",
    "day",
    "decemeb",
    "delhi",
    "detail",
    "do",
    "earth",
    "februari",
    "fli",
    "flight",
    "for",
    "from",
    "go",
    "good",
    "goodby",
    "got",
    "have",
    "head",
    "hello",
    "help",
    "hey",
    "hi",
    "how",
    "i",
    "in",
    "is",
    "it",
    "januray",
    "juli",
    "june",
    "karachi",
    "kid",
    "later",
    "leav",
    "like",
    "locat",
    "lot",
    "make",
    "march",
    "may",
    "me",
    "moon",
    "more",
    "my",
    "need",
    "needng",
    "new",
    "novemb",
    "octob",
    "on",
    "onli",
    "option",
    "paint",
    "peopl",
    "plane",
    "pleas",
    "prefer",
    "proceed",
    "purchas",
    "real",
    "reserv",
    "retunr",
    "return",
    "right",
    "round",
    "see",
    "septemb",
    "sky",
    "so",
    "thank",
    "that",
    "the",
    "there",
    "three",
    "ticket",
    "to",
    "travel",
    "two",
    "use",
    "vermont",
    "want",
    "way",
    "what",
    "where",
    "whi",
    "who",
    "will",
    "with",
    "would",
    "ye",
    "york",
    "you",
]
