from constants import cities

greetings = [
    "Hello",
    r"Hi user, welcome to infinite possibilities. How can I help you today?",
    "Hi",
    r"Hello user, welcome to infinite possibilities. How can I help you today?",
    "Greetings!",
    r"Hello user, welcome to infinite possibilities. How can I help you today?",
    "Hello",
    r"Greetings! user, welcome to infinite possibilities. How can I help you today?",
    "Hi, How is it going?",
    "Good",
    "Hi, How is it going?",
    "Fine",
    "Hi, How is it going?",
    "Okay",
    "Hi, How is it going?",
    "Great",
    "Hi, How is it going?",
    "Could be better.",
    "Hi, How is it going?",
    "Not so great.",
    "How are you doing?",
    "Good.",
    "How are you doing?",
    "Very well, thanks.",
    "How are you doing?",
    "Fine, and you?",
    "Nice to meet you.",
    "Thank you.",
    "How do you do?",
    "I'm doing well.",
    "How do you do?",
    "I'm doing well. How are you?",
    "Hi, nice to meet you.",
    "Thank you. You too.",
    "It is a pleasure to meet you.",
    "Thank you. You too.",
    "Top of the morning to you!",
    "Thank you kindly.",
    "Top of the morning to you!",
    "And the rest of the day to you.",
    "What's up?",
    "Not much.",
    "What's up?",
    "Not too much.",
    "What's up?",
    "Not much, how about you?",
    "What's up?",
    "Nothing much.",
    "Book me a flight",
    "That's what I am here for",
    "Book me a flight",
    "Sure, may I know where are you going?",
    "I want to book a flight",
    "Sure, may I know where are you going?",
    "I want airline tickets please",
    "Sure, may I know where are you going?",
    "I want to purchase airline tickets.",
    "Sure, may I know where are you going?",
    "I want to purchase airline tickets.",
    "Where are you traveling to?",
    "Book me a flight",
    "Where are you traveling to?",
    "I am travelling to ..",
    "Awesome, Should I use your current location as origin?",
    "I am Booking tickets to ..",
    "Awesome, Should I use your current location as origin?",
    "I want to go to ..",
    "Awesome, Should I use your current location as origin?",
    "I am travelling to Chicago ..",
    "Awesome, Should I use your current location as origin?",
]
